name: Build

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:

jobs:
  docker:
    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        version: [ "7.0", "7.1", "7.2", "7.3", "7.4", "8.0", "8.1" ]
      fail-fast: false

    name: docker build ${{ matrix.version }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup depot CLI
        uses: depot/setup-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitLab
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      - name: Run docker build
        run: |
          depot build --platform linux/amd64,linux/arm64 \
            --file ${{ matrix.version }}.Dockerfile \
            --tag stayallive/php:${{ matrix.version }} \
            --tag ghcr.io/stayallive/php:${{ matrix.version }} \
            --tag registry.gitlab.com/stayallive/php:${{ matrix.version }} \
            --push \
            .
        env:
          DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}
