name: Build

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  docker:
    strategy:
      matrix:
        version: [ "7.0", "7.1", "7.2", "7.3", "7.4", "8.0", "8.1" ]
      fail-fast: false

    name: docker build ${{ matrix.version }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup depot CLI
        uses: depot/setup-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run docker build
        run: depot build --platform linux/amd64,linux/arm64 --push --file ${{ matrix.version }}.Dockerfile --tag stayallive/php:${{ matrix.version }} .
        env:
          DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}
